packages:
  - name: rypm
    functions:
      - name: subs
        runtime: nodejs:18
        environment:
          VAPID_SUBJECT: mailto:ivucicev@gmail.com
          VAPID_PUBLIC_KEY: "${VAPID_PUBLIC_KEY}"
          VAPID_PRIVATE_KEY: "${VAPID_PRIVATE_KEY}"
          PST_SECRET: "${PST_SECRET}"
      - name: send
        runtime: nodejs:18
        environment:
          VAPID_SUBJECT: mailto:ivucicev@gmail.com
          VAPID_PUBLIC_KEY: "${VAPID_PUBLIC_KEY}"
          VAPID_PRIVATE_KEY: "${VAPID_PRIVATE_KEY}"
          PST_SECRET: "${PST_SECRET}"